language: node_js
node_js:
- 0.1
before_script:
- npm install -g gulp
before_install:
- openssl aes-256-cbc -K $encrypted_09c4a4e028b7_key -iv $encrypted_09c4a4e028b7_iv
  -in config.json.enc -out test/config.json -d
